### ISSUE TITLE
Add option to set 'mypy.ini' file

### ISSUE THREAD

**Issue by tebanep** [elarivie/linter-mypy#1]
First of all, thanks a lot for making this atom package! For sure it will help the Python community in the use of static typing!

I think a good addition to the linter would be to have the option to specify a per project **mypy.ini file** (using a **$PROJECT** placeholder variable). This way, users will have the control over wich options they would like to activate in a case by case basis.

For example, right now I would like to disable some Warnings regarding not found imports such as:

`Cannot find module named 'aiohttp' at line 2 col 1`
`Cannot find module named 'aiopg' at line 3 col 1`

This would be very easy if I could reference a mypy.ini file with the option: 

`--ignore-missing-imports`

As suggested by the mypy executable itself:

```
aioxample@aioxample:~$ /opt/aioxample/env/bin/mypy /opt/aioxample/aioxample/polls/aiohttpdemo_polls/main.py
/opt/aioxample/aioxample/polls/aiohttpdemo_polls/main.py:3: error: Cannot find module named 'aiohttp'
/opt/aioxample/aioxample/polls/aiohttpdemo_polls/main.py:3: note: (Perhaps setting MYPYPATH or using the "--ignore-missing-imports" flag would help)
```

The option could be, for example:

`$PROJECT/mypy.ini`

For using a mypy.ini file located in the root of the repository. This path can be given to **mypy** executable through the **--config-file** option (http://mypy.readthedocs.io/en/latest/config_file.html).

Thanks a lot!

**Comment by elarivie** [comment]
@tebanep
Hello Esteban, thanks for your feedback.

As a quick fix I added the setting "Warn Missing Imports"
It is now available with linter-mypy version 2.0.6.

This setting is On by default but you can turn it Off in which case it will behind the scene add the argument _--ignore-missing-imports_ and you won't have warnings about "_Cannot find module named..._" anymore.

I'll keep looking into your idea of supporting mypy.ini...

**Comment by tebanep** [comment]
Thanks a lot elarivie. I was just studying how to make an Atom Package to send you a pull request ;).

This addition is for sure very useful. Thanks! I'll see what I can do and give you an update later.

**Comment by elarivie** [comment]
I looked at mypy source code [where it loads the config file vs command line parameters](https://github.com/python/mypy/blob/master/mypy/main.py#L341)
and the parameters given by command line overwrites any setting provided in a mypy.ini file... Which is a good thing since else a mypy.ini file could have requested for example to not provide --show-column-numbers which is needed for the underlining of warnings.

Whenever this feature will be implemented, when a mypy.ini file is to be use the linter-mypy code will effectively need to provide the parameter "--config-file" but will also need to NOT provide pretty much all other parameters which we want to let user the possibility to define in the mypy.ini.
