### ISSUE TITLE
Add option to only check repos where mypy.ini is present

### ISSUE THREAD

**Issue by ostrokach** [elarivie/linter-mypy#12]
I am playing around with MyPy with one of my Python packages, and so far `linter-mypy` has been working great!

However, all my other repositories do not have typehints and in fact cause MyPy to crash due to python/mypy#4111. Is there some way to disable `linter-mypy` for all repositories that do not have a `mypy.ini` file in the repository root (or through another way of detecting if a repo is using mypy?)

Thanks!

**Comment by elarivie** [comment]
@ostrokach 
Hello Alexey,

Thanks for your feedback, I did reproduce the mypy internal issue that you obtain.

I notice that when a project is affected by a Mypy internal error a lot of annoying error pop-up are displayed.  Which pretty much ruin the user experience and disabling linter-mypy is pretty much currently the only available option to keep working without those pop-up.

What I will implement:

1. Improve the error pop-up so that any kind of Mypy internal error also display the full Mypy stacktrace to help bug reporting ("--show-traceback").

2. Add a setting to turn-off Mypy internal error related pop-up (obviously when internal error occurs no lint warning will be shown for this specific Mypy run which will looks like as if they were deactivated for a given project).

3. Add a button on the internal error pop-up to turn off pop-up of internal error.

**Comment by elarivie** [comment]
This is fix in linter-mypy v2.4.2

**Comment by ostrokach** [comment]
The fix is working great! Thanks!!
