### ISSUE TITLE
Can't detect mypy anymore

### ISSUE THREAD

**Issue by nmatthews-asapp** [elarivie/linter-mypy#19]
I use pyenv, and have mypy installed in an environment I use for python-related plugins: `atom_env_3.6.7`. I set the path of mypy to reflect the correct python installation.

The error message says
```
The python package mypy does not seem to be installed. Install it with:

/my/path/to/home/.pyenv/versions/3.6.7/envs/atom_env_3.6.7/bin/python -m pip install mypy
```

But if I run 
```
/my/path/to/home/.pyenv/versions/3.6.7/envs/atom_env_3.6.7/bin/python -m pip list
```
I get 
```
Package                Version
---------------------- -------
autopep8               1.4.3
...
mypy                   0.700
...
```

And running the suggested install command does nothing because it's already installed

This started happening recently, so in the last one or two updates

**Comment by elarivie** [comment]
Hello @nmatthews-asapp,

- Can you try running the following:
`/my/path/to/home/.pyenv/versions/3.6.7/envs/atom_env_3.6.7/bin/python -m mypy --version`

It will either show the mypy version or "**No module named mypy**"

From your your issue description I am pretty sure it will print "No module named mypy"

Because this is the string which [when detected by linter-mypy](https://github.com/elarivie/linter-mypy/blob/master/lib/init.coffee#L665) triggers the [pop-up that you receive](https://github.com/elarivie/linter-mypy/blob/master/lib/init.coffee#L678) about "mypy does not seem to be installed"

I am not an expert of pyenv but I am pretty sure that you need to validate your pyenv configuration.

Note that the suggested install command that linter-mypy displays in the pop-up is a "suggestion" which works most of the time" but in your python virtual environment configuration maybe it is another command line that you need to use.

Maybe pyenv is changing some environment variable and if you don't launch atom within that context than the python installation is in an hybrid/unusable state.

**Note:** does pyenv have some kind of activation command which needs to be launch first to activate the environment (which need to be call prior to launch the installation of mypy?, before launching atom?)

Let me know if you make progress or find the solution to your issue.

**Note:** See #18 which was recently solve and is also about a linter-mypy user using a python virtual environment, it may contains information which could help you with the issue that you have.

**Comment by CesarLanderos** [comment]
![image](https://user-images.githubusercontent.com/815951/55909422-9938a780-5ba1-11e9-8ce2-a6923c706d25.png)

i get this and doing `/.../python -m mypy --version` gives me:

`mypy 0.670`

**Comment by CesarLanderos** [comment]
it used to just work before i updated the package

**Comment by elarivie** [comment]
Hello @CesarLanderos,

**Note:** The issue that you describe is different than the one reported by @nmatthews-asapp 

**Note.** linter-mypy always aim to support the "latest" version of Mypy so from time to time [mypy](http://mypy-lang.org/) must be updated.

@CesarLanderos, in your situation you have to update Mypy has the pop-up is telling you, from the details that you provided I see that you have mypy 0.670 installed... but linter-mypy has recently been updated to fully support the latest version of Mypy which is currently 0.700.  So effectively mypy 0.700 has command line arguments which were not present in prior version.

Within the pop-up the suggested command line that is shown in the pop-up contains:
... -m pip install **-U** mypy
The **-U** parameter is to "Update"

**Note:**  From the python path in your screen shot I see that you are using a python environment, so maybe in your situation the actual command line to update mypy is different.

@CesarLanderos  Let me know if this solves your issue.

@nmatthews-asapp Did you resolve your issue?

**Comment by CesarLanderos** [comment]
thanks for the response, i do agree, this is a different issue.

your suggestion did not fix the issue, this is what i have now when i print the version:

`mypy 0.700`

**Comment by CesarLanderos** [comment]
ah! ignore that message, it is working now 😅 

thanks!!!

i realize that this was my fault for not actually reading the error message 😓

**Comment by nmatthews-asapp** [comment]
@elarivie 

When I run 
```
/path/to/home/.pyenv/versions/3.6.7/envs/atom_env_3.6.7/bin/python -m mypy --version
```
I get: `mypy 0.701`
I do activate my environment before starting Atom and given that, I can also run `python -m mypy --version` and get the same result

**Comment by elarivie** [comment]
4 Months without new information, closing this issue...

**Comment by str225** [comment]
I'm having the same problem: If i uninstall mypy globally, create a virtual environment and install mypy on it. I can run mypy from the terminal from inside the virtual environment, but, even after running atom from inside the venv, linter-mypy can't find mypy.

Shouldn't it use the venv mypy instead of the global one ?
