### ISSUE TITLE
Does not recognise typed_ast package

### ISSUE THREAD

**Issue by ShadowLNC** [elarivie/linter-mypy#22]
When I lint, the following notification is shown:

The typed_ast package is not installed. You can install it with `python3 -m pip install typed-ast`.

I understand this may be an issue with `mypy` itself (I've found [a related issue](https://github.com/python/mypy/issues/2902)), however running `python -m mypy` doesn't have this error.

`pip freeze` results (virtual environment):
```
appdirs==1.4.3
astroid==2.3.3
attrs==19.3.0
black==19.10b0
Click==7.0
isort==4.3.21
lazy-object-proxy==1.4.3
mccabe==0.6.1
mypy==0.750
mypy-extensions==0.4.3
pathspec==0.6.0
pkg-resources==0.0.0
pycodestyle==2.5.0
pydocstyle==4.0.1
pyflakes==2.1.1
pylama==7.7.1
pylama-pylint==3.1.1
pylint==2.4.4
regex==2019.11.1
six==1.13.0
snowballstemmer==2.0.0
toml==0.10.0
typed-ast==1.4.0
typing-extensions==3.7.4.1
wrapt==1.11.2
```

linter-mypy version 2.6.8 running on Ubuntu with Atom 1.41.0 x64.

It also took me a while to identify the error as being from this package.

**Comment by elarivie** [comment]
Hello @ShadowLNC,

**TLTR:** Your issue seems to be relatedd to a python2 vs python3 mixup.

I don't know if they are typos in your issue description but sometimes you mention 'python' and sometimes your mention 'python3'.

On ubuntu 'python' is pointing to python2

Note that python2 end of life is January 1st 2020... so you should be using python3 everywhere by now.

I can confirm that the message that your receive is not a linter-mypy bug, in fact linter-mypy is perfectly doing its job of showing you the error message provided by mypy.


Make sure that the linter-mypy setting is using python3 (its the default value unless you have written something in that textbox)

Effectively mypy needs typed-ast to run and if you run the command

    python3 -m pip install -U typed-ast
It will install it

You can try to uninstall it first just in case (to start clean)

    python3 -m pip uninstall typed-ast
    python3 -m pip uninstall mypy

    python3 -m pip install -U mypy
    python3 -m pip install -U typed-ast


But then even if they are are correctly installed in the python3 packages... if you are using the executable of python2 it will keep complaining that they are not installed.


Let me know if it solves your issue.

**Comment by ShadowLNC** [comment]
Thanks for the response!
I'm using a virtual environment, hence the `python` binary (which is a Python3 virtual environment), is it required to use the user packages directory? I'm not sure how `mypy` is being invoked, and whether `typed-ast` is actually available (on the path) at runtime.
My executable path for linter-mypy is `/home/scott/.atom/venv/bin/python`.

**Comment by elarivie** [comment]
@ShadowLNC  I just wrote this small script to help you debug your environment:
Use this script as a wrapper to inspect parameters and environment variables being use

	#!/bin/sh

	# You can use this script to debug linter-mypy in your environment.
	# It basically wrap python3 calls

	#1 - Define an output file somewhere on your disk:
	outputfile=~/linter-mypy_debug.txt

	#2 - Make this script executable (chmod +x linter-mypy_X)

	#3 - Change linter-mypy settings to use the current script as a pseudo python executable.

	#4 - Within atom trigger a lint process of a file.

	#5 - Look at the content of the outputfile

	# Clear the output file content
	echo "" > "$outputfile"


	# The following command will send every parameters received to the output file
	echo "PARAMETERS" >> "$outputfile"
	echo "$@" >> "$outputfile"

	# The following commands will send some important environment variables to the output file

	echo "PATH" >> "$outputfile"
	echo $PATH >> "$outputfile"

	echo "MYPYPATH" >> "$outputfile"
	echo $MYPYPATH >> "$outputfile"

	echo "PYTHONPATH" >> "$outputfile"
	echo $PYTHONPATH >> "$outputfile"

	# The following command will send the current working directory path to the output file

	echo "Current Working Directory" >> "$outputfile"
	pwd >> "$outputfile"


	# Forward the call to python3 including all the parameters received so that linter-mypy gets lint output
	python3 "$@"

**Comment by ShadowLNC** [comment]
Thanks :smile: 

(Apologies - I responded yesterday but it seems it didn't submit?)

Seems like somehow the `PYTHONPATH` environment variable is being modified and is copied from the `PYTHONPATH` setting from the linter-pylint plugin. This doesn't always happen, so I suspect a race condition (and linter-pylint is probably modifying the environment which is then picked up by linter-mypy). When `PYTHONPATH` is empty, everything works as expected.

I've filed the bug with linter-pylint as referenced above, but in the meantime, would it please be possible to add a setting to linter-mypy for the `PYTHONPATH` variable?

**Comment by elarivie** [comment]
Hi @ShadowLNC,

In linter-mypy v2.6.9
1- PYTHONPATH can now be specified
2- There is now a more user friendly message if typed-ast is not present
