### ISSUE TITLE
Option to start the mypy process from the (Atom) project directory?

### ISSUE THREAD

**Issue by jmanuel1** [elarivie/linter-mypy#24]
I'm using type stubs in a project mine, and I put them under the `$PROJECT_PATH/stubs/` directory. In [my `mypy.ini`](https://github.com/jmanuel1/concat/blob/unstable/mypy.ini), I set `mypy_path` to `stubs/` (it is a relative path on purpose). linter-mypy does not seem to be able to find my stubs, and behaves as if they are not there. I believe this is because linter-mypy runs mypy from the file system root, leading mypy to look for a `/stubs/` directory which I don't have. I'm currently working around this issue by using [my fork](https://github.com/jmanuel1/linter-mypy/tree/project-path-as-cwd) of this package that runs mypy in `$PROJECT_PATH`.

According to my understanding of issue #4, linter-mypy runs mypy from the file system root to avoid work around a mypy limitation with finding the top-level package in a project. I guess this behavior shouldn't change for most users in order to avoid that mypy limitation. Maybe there should be an option to change the working directory for the mypy process?

**Comment by elarivie** [comment]
Hello @jmanuel1 

**Personal comment:** It is kinda counter intuitive that relative path defined in the configuration file are base on the CWD of future mypy processes instead of being base on the configuration file path.  This sounds like a mypy bug to me.


I just did a commit with a possible solution to your issue:
https://github.com/elarivie/linter-mypy/commit/b74c0e5a6aaeac80a0b4118fdb237ad9e70d7028

Could you give it a try and tell me if it fixes your issue… if it does I'll include the changes in the next release of linter-mypy I am planning to do in the next few days.

The fix that I did is to set the CWD to the root as it is right now but not if a configuration file is provided.

If a configuration file is provided, the CWD is instead  set to the folder containing the configuration file.

Doing so I expect that relative paths defined within the configuration file will point to the expected folder.

**Comment by jmanuel1** [comment]
Hi @elarivie, the fix works on my end, thank you! It's too bad that mypy can be kind of surprising when it comes to paths :(

**Comment by elarivie** [comment]
Hi @jmanuel1, it is now part of linter-mypy **v2.6.9**
